### PR TITLE
Fixes needed to enable compilation with gcc 13

### PR DESCRIPTION
**Pull request by mprather**
This fix addresses raised by gcc 13.  See https://github.com/dotnet/aspnetcore/issues/49784 for details.

### CODE REVIEW

**Comment by BrennanConroy** [comment]
Thanks 😃 
Could you sign the CLA?

**Comment by mprather** [comment]
@microsoft-github-policy-service agree

**Comment by mprather** [comment]
@BrennanConroy I'm a little confused how to sign the CLA. The link to the policy has instructions on how to install, etc. This seems like it's for orgs but I read further down, there are some additional links that appear more IC-centric. Those state I should have received a comment to which I can reply. I don't recall this being so confusing for a vcpkg pr that I submitted a year ago, perhaps something changed and the cla needs to be signed again?  I'll do my best to get this sorted out.

**Comment by BrennanConroy** [comment]
Try `@dotnet-policy-service agree`? And if that doesn't work, you could try opening a PR in https://github.com/dotnet/aspnetcore and signing the CLA there, it might be that this org needs some updates for the bot to work properly?

**Comment by mprather** [comment]
@dotnet-policy-service agree

**Comment by mprather** [comment]
@BrennanConroy thanks

**Comment by mprather** [comment]
@BrennanConroy any chance the project can be tagged with a new version that picks up this change? this can then be used by the vcpkg port. otherwise, any system using gcc 13 (i.e. arch and alpine by default) runs into a build break.

**Comment by FrankXie05** [comment]
@BrennanConroy Will there be a new version released in the near future to adapt to the fixed issues?

**Pull request merged**
