### PR TITLE
fixed deadlock on Stop when in connecting state

### PR DESCRIPTION
**Pull request by gonzo-coder**
My proposal to fix:
https://github.com/dotnet/aspnetcore/issues/25729

### CODE REVIEW

**Review by BrennanConroy — APPROVED** [review]
Looks good thanks!

Could we also add this to line 151 to cover all the spots?

**Comment by gonzo-coder** [comment]
> Looks good thanks!
> 
> Could we also add this to line 151 to cover all the spots?

Sure!

**Comment by BrennanConroy** [comment]
@gonzo-coder Do you have time to make the update? Otherwise I can see if I have write permissions to your branch to update it.

**Comment by gonzo-coder** [comment]
@BrennanConroy Ok! I'll give you write permission to my fork, because I have no time right now to test properly this change. But! I have tested current code in my fork in production and it worked well. Original issue fixed. Is this 151-line fix really worth a hassle? Better is often the enemy of good enough.

**Comment by BrennanConroy** [comment]
It follows the exact same pattern as the rest of the code changes, and it wont make things worse. I'll fix it 👍

**Comment by BrennanConroy** [comment]
Thanks for fixing this!

**Pull request merged**
